fix: css styles and select component changed
InctaRepo/Inctagram pull request #11
Opened 2023-08-22 06:31 UTC by Elena1789

2023-08-22 06:39 UTC, PetukhovArt commented on src/components/ui/selectbox/Selectbox.tsx
> +  onValueChange?: (value: string) => void
А если выбранное значение это число? 
Нужно предусмотреть чтобы мог приходить массив строк / чисел

2023-08-22 06:42 UTC, PetukhovArt commented on src/components/ui/selectbox/Selectbox.tsx
> +    const options = [{value: 'select-box'}, {value: 'select-box'}, {value: 'select-box'}]
ты можешь в деструктуризации пропс указывать значение опций по умолчанию

2023-08-22 06:44 UTC, PetukhovArt commented on src/components/ui/selectbox/Selectbox.tsx
> +    value={value}
в компоненте нужен локальный стейт, при выборе значения селекта , состояние обновляется и в шапке селекта отображается текущее состояние

2023-08-22 06:44 UTC, PetukhovArt commented on src/components/ui/selectbox/Selectbox.tsx
> +        defaultValue={defaultValue}
как правило первое значение из опций если они существуют в пропс // либо ....

2023-08-22 06:48 UTC, PetukhovArt commented on src/components/ui/selectbox/selectbox.module.scss
> +.label {
Ты же оборачиваешь label в типографи , зачем дублирование стилей ?

2023-08-22 06:50 UTC, PetukhovArt requested changes
см комментарии по коммиту

2023-08-22 06:51 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +  onValueChange?: (value: string) => void
А зачем ? Здесь ведь будет список языков ?

2023-08-22 06:58 UTC, PetukhovArt commented on src/components/ui/selectbox/Selectbox.tsx
> +  onValueChange?: (value: string) => void
Этот селект может понадобится в других компонентах. Лучше сделать сразу универсальный , без каких-либо хардкодов , это касается и логики и стилей , должна быть возможность прокинуть класснейм в пропс , для перестилизации.
Затем ты его можешь использовать в любых проектах , единственной заменить стили /radix , на что-то другое например

2023-08-22 07:00 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +  onValueChange?: (value: string) => void
хорошо, договорилилсь

2023-08-22 13:39 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +  onValueChange?: (value: string) => void
done

2023-08-22 14:45 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +    const options = [{value: 'select-box'}, {value: 'select-box'}, {value: 'select-box'}]
done

2023-08-22 15:05 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +    value={value}
done

2023-08-22 15:36 UTC, Elena1789 commented on src/components/ui/selectbox/selectbox.module.scss
> +.label {
done

2023-08-22 19:54 UTC, Elena1789 commented on src/components/ui/selectbox/Selectbox.tsx
> +        defaultValue={defaultValue}
done

2023-08-23 09:49 UTC, Nikita1025 approved these changes

2023-08-23 14:41 UTC, Nikita1025 approved these changes

2023-08-23 15:11 UTC, czenturion approved these changes

2023-08-24 06:39 UTC, PetukhovArt approved these changes

2023-08-24 06:39 UTC, merged